//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taller_Carros.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_factura_reparacion
    {
        public int id { get; set; }
        public int id_factura { get; set; }
        public int id_reparacion { get; set; }
        public Nullable<decimal> costo { get; set; }
    
        public virtual Factura Factura { get; set; }
        public virtual Reparacion Reparacion { get; set; }
    }
}
