//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taller_Carros.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reparacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reparacion()
        {
            this.detalle_factura_reparacion = new HashSet<detalle_factura_reparacion>();
            this.detalle_reparacion_empleado = new HashSet<detalle_reparacion_empleado>();
            this.detalle_vehiculo_reparacion = new HashSet<detalle_vehiculo_reparacion>();
        }
    
        public int id_reparacion { get; set; }
        public int id_tipo_reparacion { get; set; }
        public string nombre { get; set; }
        public decimal costo_reparacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_factura_reparacion> detalle_factura_reparacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_reparacion_empleado> detalle_reparacion_empleado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_vehiculo_reparacion> detalle_vehiculo_reparacion { get; set; }
        public virtual Tipo_reparacion Tipo_reparacion { get; set; }
    }
}
