//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taller_Carros.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servicio_adicional
    {
        public int id_servicio_adicional { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public decimal precio { get; set; }
        public int documento_empleado { get; set; }
        public int id_factura { get; set; }
        public string id_vehiculo { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual Factura Factura { get; set; }
        public virtual Vehiculo Vehiculo { get; set; }
    }
}
