//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taller_Carros.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehiculo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehiculo()
        {
            this.detalle_vehiculo_reparacion = new HashSet<detalle_vehiculo_reparacion>();
            this.detalle_vehiculo_servicio = new HashSet<detalle_vehiculo_servicio>();
        }
    
        public string id_vehiculo { get; set; }
        public int id_tipo_vehiculo { get; set; }
        public int documento_cliente { get; set; }
        public int id_modelo { get; set; }
        public int anio { get; set; }
        public int kilometraje { get; set; }
        public int numero_puertas { get; set; }
        public int id_color { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Color Color { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_vehiculo_reparacion> detalle_vehiculo_reparacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_vehiculo_servicio> detalle_vehiculo_servicio { get; set; }
        public virtual Modelo Modelo { get; set; }
        public virtual Tipo_Vehiculo Tipo_Vehiculo { get; set; }
    }
}
